package loop

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/openzot/openzot/internal/catalogue"
	"github.com/openzot/openzot/internal/compaction"
	"github.com/openzot/openzot/internal/provider"
	"github.com/openzot/openzot/internal/thread"
	"github.com/openzot/openzot/internal/tokenizer"
)

// ToolHandler executes a tool call.
type ToolHandler func(ctx context.Context, arguments map[string]any) (any, error)

// ToolDefinition is a tool offered to the model.
type ToolDefinition struct {
	Name        string
	Description string
	Parameters  map[string]any
	Handler     ToolHandler
}

// Skill is a capability described to the model in the system prompt.
//
// Path is not resolved here. The model is told where the instructions live and
// reads them with a file tool if it decides to - which is what keeps a skill
// inert text rather than an implicit capability.
type Skill struct {
	Name        string
	Description string
	Path        string

	// Hint tells the model how to reach the instructions - which differs
	// between a skill on disk and one compiled into the binary. Generated by the
	// loader rather than authored, so the same SKILL.md works either way.
	Hint string
}

// Options configures a run.
type Options struct {
	// Client is the provider connection.
	Client *provider.Client

	// Backstory is the system prompt.
	Backstory string

	// Messages seeds the conversation.
	Messages []Message

	// Tools the model may call, keyed by name.
	Tools map[string]ToolDefinition

	// Skills are rendered into the system prompt.
	Skills []Skill

	// MaxIterations, MaxCalls, MaxContinuations, MaxCycles, MaxEmpties bound the
	// run. Zero uses the corresponding default.
	MaxIterations    int
	MaxCalls         int
	MaxContinuations int
	MaxCycles        int
	MaxEmpties       int

	// MaxSettles enables settle mode when positive: the run finishes only when
	// the model calls a terminal tool. This is what replaces deciding a task is
	// done because the answer contained the word "completed".
	MaxSettles int

	// MaxTokens bounds a single response.
	MaxTokens *int
}

// MessageType identifies what a message is.
//
// A named type rather than a bare string: these values decide how a message is
// rendered to the provider, whether the runaway backstop scans it, and whether
// compaction may summarise it away. A typo in a string literal would silently
// route a message down the wrong path - a backstory summarised as ordinary
// history, say - and nothing would report it.
type MessageType string

// The message types the loop understands.
const (
	// TypeUser is input from the operator, and the channel the loop injects its
	// own notices on.
	TypeUser MessageType = "user"

	// TypeBot is the model's answer.
	TypeBot MessageType = "bot"

	// TypeReasoning is the model's scratchpad. Never replayed to the provider,
	// and exempt from the runaway-text backstop.
	TypeReasoning MessageType = "reasoning"

	// TypeActivity is one half of a tool-call pair.
	TypeActivity MessageType = "activity"

	// TypeBackstory is system context. Never summarised, and always ordered
	// ahead of everything else.
	TypeBackstory MessageType = "backstory"

	// TypeContext is injected context, including a compaction summary.
	TypeContext MessageType = "context"
)

// Message is one entry in the conversation.
type Message struct {
	Type MessageType `json:"type"`
	Text string      `json:"text"`

	// Activity is the tool call this message carries, on a TypeActivity
	// message. Nil on every other type.
	Activity *Activity `json:"activity,omitempty"`
}

// Result is the outcome of a run.
type Result struct {
	// Reason is why the run ended.
	Reason StopReason

	// Message is a human-readable explanation.
	Message string

	// Messages is the conversation as it ended.
	Messages []Message

	// Budget is what the run spent.
	Budget Budget

	// Err is set when Reason is StopError.
	Err error
}

// Engine runs conversations.
type Engine struct {
	options Options

	maxIterations    int
	maxCalls         int
	maxContinuations int
	maxCycles        int
	maxEmpties       int
	maxSettles       int

	model       string
	inputBudget int

	// toolTokens caches the cost of the tool schemas, which are identical on
	// every request of a run and would otherwise be re-counted each round.
	toolTokens int
}

// toolSchemaTokens is what the tool definitions cost on the wire.
//
// They are sent with every request and can be substantial - a dozen tools with
// detailed JSON Schema runs to thousands of tokens - so leaving them out of the
// budget is how a thread that "fits" gets rejected.
func (e *Engine) toolSchemaTokens(tools []provider.Tool) int {
	if e.toolTokens > 0 || len(tools) == 0 {
		return e.toolTokens
	}

	encoded, err := json.Marshal(tools)
	if err != nil {
		return 0
	}

	e.toolTokens = tokenizer.Count(e.model, string(encoded))

	return e.toolTokens
}

// New creates an engine, applying defaults.
func New(options Options) (*Engine, error) {
	if options.Client == nil {
		return nil, errors.New("loop: no provider client")
	}

	pick := func(value, fallback int) int {
		if value > 0 {
			return value
		}

		return fallback
	}

	model := options.Client.Config().Model

	budget := catalogue.InputBudget(model)

	if budget < MinInputTokens {
		budget = MinInputTokens
	}

	return &Engine{
		options:          options,
		model:            model,
		maxIterations:    pick(options.MaxIterations, DefaultMaxIterations),
		maxCalls:         pick(options.MaxCalls, DefaultMaxCalls),
		maxContinuations: pick(options.MaxContinuations, DefaultMaxContinuations),
		maxCycles:        pick(options.MaxCycles, DefaultMaxCycles),
		maxEmpties:       pick(options.MaxEmpties, DefaultMaxEmpties),
		maxSettles:       options.MaxSettles,
		inputBudget:      budget,
	}, nil
}

// settleMode reports whether the run ends only on a terminal tool call.
func (e *Engine) settleMode() bool {
	return e.maxSettles > 0
}

// Run drives the conversation to a conclusion, emitting events as it goes.
//
// The returned channel closes when the run ends; the final event carries the
// Result. Events are delivered synchronously, so a slow consumer throttles the
// run rather than dropping anything.
func (e *Engine) Run(ctx context.Context, emit func(Event)) Result {
	if emit == nil {
		emit = func(Event) {}
	}

	messages := append([]Message(nil), e.options.Messages...)

	budget := Budget{}

	tools := e.toolDefinitions()

	for {
		if err := ctx.Err(); err != nil {
			return e.finish(messages, budget, StopAborted, "run cancelled", err)
		}

		if budget.Iterations >= e.maxIterations {
			return e.finish(messages, budget, StopIterations,
				fmt.Sprintf("stopped after %d iterations", budget.Iterations), nil)
		}

		budget.Iterations++

		emit(Event{Kind: EventIteration, Iteration: budget.Iterations})

		request, err := e.buildRequest(messages, tools)
		if err != nil {
			return e.finish(messages, budget, StopError, "could not assemble the request", err)
		}

		turn, err := e.runTurn(ctx, request, emit)

		if err != nil {
			// a context-limit rejection is recoverable: compact and retry
			if limit, ok := provider.DetectContextLimit(err); ok && budget.Continuations < e.maxContinuations {
				budget.Continuations++

				// @note the provider's stated window beats the local estimate.
				// A rejection is precisely the case where the catalogue was
				// wrong - an uncatalogued model, or a provider serving a smaller
				// variant - so believing the error is what makes the retry fit
				// instead of guessing again.
				if limit.SuggestedLimit > 0 && limit.SuggestedLimit < e.inputBudget {
					e.inputBudget = limit.SuggestedLimit

					emit(Event{Kind: EventRetry, Text: fmt.Sprintf(
						"provider reported a %d token window; retrying under %d",
						limit.MaxTokens, limit.SuggestedLimit)})
				}

				compacted, ok := e.compact(messages)

				if ok {
					messages = compacted

					continue
				}

				// even without a split to make, a lowered budget is worth one
				// more attempt - the thread builder will simply trim harder
				if limit.SuggestedLimit > 0 {
					continue
				}
			}

			if provider.IsRetriable(err) && budget.Continuations < e.maxContinuations {
				budget.Continuations++

				emit(Event{Kind: EventRetry, Text: err.Error()})

				continue
			}

			return e.finish(messages, budget, StopError, "the provider failed", err)
		}

		// record what the model produced

		if turn.Reasoning != "" {
			messages = append(messages, Message{Type: TypeReasoning, Text: turn.Reasoning})

			emit(Event{Kind: EventMessage, MessageType: TypeReasoning, Text: turn.Reasoning})
		}

		if turn.Text != "" {
			messages = append(messages, Message{Type: TypeBot, Text: turn.Text})

			emit(Event{Kind: EventMessage, MessageType: TypeBot, Text: turn.Text})
		}

		// a truncated answer is continued rather than accepted

		if turn.FinishReason == provider.FinishLength {
			if budget.Continuations >= e.maxContinuations {
				return e.finish(messages, budget, StopContinuations,
					"the model kept running out of output space", nil)
			}

			budget.Continuations++

			messages = append(messages, Message{Type: TypeUser, Text: truncationNotice()})

			continue
		}

		// terminal tool calls end the run before anything else is dispatched

		if reason, detail, terminal := e.terminalCall(turn.ToolCalls); terminal {
			return e.finish(messages, budget, reason, detail, nil)
		}

		if len(turn.ToolCalls) > 0 {
			var stop *Result

			messages, stop = e.dispatch(ctx, messages, turn.ToolCalls, &budget, emit)

			if stop != nil {
				return *stop
			}

			// the loop only checks for repetition once tools have run, because
			// a repetition is a repetition of *actions*
			if next, stop := e.checkCycle(messages, &budget); stop != nil {
				return *stop
			} else if next != nil {
				messages = next
			}

			continue
		}

		// nothing at all: no text, no tool call

		if turn.Text == "" && turn.Reasoning == "" {
			if budget.Empties >= e.maxEmpties {
				return e.finish(messages, budget, StopEmpty,
					"the model repeatedly produced nothing", nil)
			}

			budget.Empties++

			messages = append(messages, Message{Type: TypeUser, Text: emptyNotice()})

			continue
		}

		// the model stopped talking

		if e.settleMode() {
			if budget.Settles >= e.maxSettles {
				return e.finish(messages, budget, StopUnsettled,
					"the model stopped without recording an outcome", nil)
			}

			budget.Settles++

			messages = append(messages, Message{Type: TypeUser, Text: settleNotice()})

			continue
		}

		return e.finish(messages, budget, StopStop, turn.Text, nil)
	}
}

// turnResult is what one model call produced.
type turnResult struct {
	Text         string
	Reasoning    string
	ToolCalls    []provider.ToolCall
	FinishReason string
}

// runTurn performs a single model call, streaming its output through emit and
// watching for a runaway.
func (e *Engine) runTurn(ctx context.Context, request provider.Request, emit func(Event)) (turnResult, error) {
	var (
		text      strings.Builder
		reasoning strings.Builder
		result    turnResult
	)

	minChars := RunawayGuardMinChars

	guard := thread.NewGuard(thread.GuardOptions{MinChars: &minChars})

	for event := range e.options.Client.Stream(ctx, request) {
		if event.Err != nil {
			return turnResult{}, event.Err
		}

		if event.Token != "" {
			text.WriteString(event.Token)

			emit(Event{Kind: EventToken, Text: event.Token})

			// the streaming guard cuts a degenerate turn short rather than
			// letting it burn the whole output budget
			if guard.Push(event.Token) {
				result.Text = text.String()
				result.Reasoning = reasoning.String()
				result.FinishReason = provider.FinishStop

				if reason := guard.Reason(); reason != nil {
					emit(Event{Kind: EventRunaway, Text: reason.Text})
				}

				return result, nil
			}
		}

		if event.ReasoningToken != "" {
			reasoning.WriteString(event.ReasoningToken)

			emit(Event{Kind: EventReasoningToken, Text: event.ReasoningToken})
		}

		if len(event.ToolCalls) > 0 {
			result.ToolCalls = event.ToolCalls
		}

		if event.FinishReason != "" {
			result.FinishReason = event.FinishReason
		}
	}

	result.Text = text.String()
	result.Reasoning = reasoning.String()

	return result, nil
}

// terminalCall reports whether the model ended the run with a terminal tool.
func (e *Engine) terminalCall(calls []provider.ToolCall) (StopReason, string, bool) {
	if !e.settleMode() {
		return "", "", false
	}

	for _, call := range calls {
		switch call.Function.Name {
		case SuccessTool:
			return StopSettled, terminalDetail(call, "summary", "task complete"), true
		case FailureTool:
			return StopSettled, terminalDetail(call, "reason", "task failed"), true
		}
	}

	return "", "", false
}

// terminalDetail pulls the explanation out of a terminal call's arguments.
func terminalDetail(call provider.ToolCall, key, fallback string) string {
	arguments, err := provider.DecodeArguments(call)
	if err != nil {
		return fallback
	}

	if value, ok := arguments[key].(string); ok && value != "" {
		return value
	}

	return fallback
}

// dispatch executes the tools the model requested and appends the results.
//
// Each call becomes a request/response activity pair. The pairing is not
// cosmetic: a provider rejects a turn whose tool result has no matching call, so
// the two must be appended together and must survive trimming together.
func (e *Engine) dispatch(
	ctx context.Context,
	messages []Message,
	calls []provider.ToolCall,
	budget *Budget,
	emit func(Event),
) ([]Message, *Result) {
	for _, call := range calls {
		if budget.Calls >= e.maxCalls {
			result := e.finish(messages, *budget, StopCalls,
				fmt.Sprintf("stopped after %d tool calls", budget.Calls), nil)

			return messages, &result
		}

		budget.Calls++

		name := call.Function.Name

		messages = append(messages, activityMessage(ActivityRequest, call, nil, ""))

		definition, known := e.options.Tools[name]

		// decode before announcing, so the event carries usable arguments
		arguments, decodeErr := provider.DecodeArguments(call)

		emit(Event{Kind: EventToolCallStart, Tool: name, Args: arguments, Text: call.Function.Arguments})

		if !known {
			failure := fmt.Sprintf("no such tool: %s", name)

			emit(Event{Kind: EventToolCallError, Tool: name, Text: failure})

			messages = append(messages, activityMessage(ActivityResponse, call, nil, failure))

			continue
		}

		if decodeErr != nil {
			emit(Event{Kind: EventToolCallError, Tool: name, Text: decodeErr.Error()})

			messages = append(messages, activityMessage(ActivityResponse, call, nil, decodeErr.Error()))

			continue
		}

		output, err := definition.Handler(ctx, arguments)

		if err != nil {
			emit(Event{Kind: EventToolCallError, Tool: name, Text: err.Error()})

			messages = append(messages, activityMessage(ActivityResponse, call, nil, err.Error()))

			continue
		}

		emit(Event{Kind: EventToolCallEnd, Tool: name, Result: output})

		messages = append(messages, activityMessage(ActivityResponse, call, output, ""))

		// warn while there is still budget left to act on the warning
		if !budget.budgetWarned {
			remaining := e.maxCalls - budget.Calls

			if remaining <= callBudgetLowThreshold(e.maxCalls) {
				budget.budgetWarned = true

				messages = append(messages, Message{Type: TypeUser, Text: callBudgetLowNotice(remaining)})
			}
		}
	}

	return messages, nil
}

// activityMessage renders one half of a tool-call pair.
func activityMessage(kind ActivityKind, call provider.ToolCall, result any, failure string) Message {
	activity := &Activity{
		Kind:      kind,
		ID:        call.ID,
		Name:      call.Function.Name,
		Arguments: call.Function.Arguments,
	}

	if kind == ActivityResponse {
		activity.Result = result
		activity.Failure = failure
	}

	// the text is what the model is shown; a request shows nothing, because the
	// call itself is carried in the wire format's tool_calls field
	return Message{
		Type:     TypeActivity,
		Text:     activity.ResultText(),
		Activity: activity,
	}
}

// checkCycle looks for repetition and nudges the model, or stops the run once
// nudging has failed enough times.
func (e *Engine) checkCycle(messages []Message, budget *Budget) ([]Message, *Result) {
	detected := thread.DescribeThreadCycle(toThreadMessages(messages), thread.CycleOptions{})

	if detected == "" {
		return nil, nil
	}

	if budget.Cycles >= e.maxCycles {
		result := e.finish(messages, *budget, StopCycle,
			fmt.Sprintf("the model kept repeating itself (%s)", detected), nil)

		return nil, &result
	}

	budget.Cycles++

	return append(messages, Message{Type: TypeUser, Text: cycleNotice(cycleDetail(detected))}), nil
}

// cycleDetail turns a heuristic name into something the model can act on.
func cycleDetail(heuristic string) string {
	switch heuristic {
	case "repeated_result_run":
		return "you have called the same tool with the same arguments and received the same result several times"
	case "repeated_activity_tail":
		return "your recent tool calls keep cycling through the same small set of actions"
	case "repeated_suffix":
		return "the last few turns of this conversation are an exact repeat of the ones before them"
	case "repeated_message_text_run":
		return "your last answer repeated the same sentences over and over"
	default:
		return ""
	}
}

// compact condenses the conversation when it no longer fits.
func (e *Engine) compact(messages []Message) ([]Message, bool) {
	check := compaction.CheckCompaction(toCompactionMessages(messages), compaction.Options{
		Model:     e.model,
		MaxTokens: e.inputBudget,
	})

	if !check.ShouldCompact {
		return nil, false
	}

	// @note the summary is produced without a model call: asking the provider to
	// summarise is what got us here, and a request that was just rejected for
	// being too large cannot be retried as-is. A structural summary is worse
	// than an LLM one but always available.
	summary := structuralSummary(check.MessagesToSummarize)

	merged := compaction.ApplySummary(check.MessagesToKeep, summary, check.MessagesToSummarize)

	return fromCompactionMessages(merged), true
}

// structuralSummary condenses history without a model call.
func structuralSummary(messages []compaction.Message) string {
	var builder strings.Builder

	builder.WriteString("Earlier turns, condensed:\n")

	for _, message := range messages {
		text := strings.TrimSpace(message.Text)

		if text == "" {
			continue
		}

		if len(text) > 200 {
			text = text[:200] + "…"
		}

		fmt.Fprintf(&builder, "- [%s] %s\n", message.Type, text)
	}

	return builder.String()
}

// buildRequest assembles the provider request, trimming the conversation to fit.
func (e *Engine) buildRequest(messages []Message, tools []provider.Tool) (provider.Request, error) {
	backstory := e.backstory()

	// reserve room for the system prompt and the tool schemas, both of which are
	// sent on every request and neither of which the thread builder sees
	reserved := tokenizer.Count(e.model, backstory) + e.toolSchemaTokens(tools)

	budget := e.inputBudget - reserved

	if budget < MinInputTokens/2 {
		budget = MinInputTokens / 2
	}

	built, err := thread.BuildThread(thread.BuildOptions{
		Messages:  toThreadMessages(messages),
		MaxTokens: float64(budget),

		// keep the most recent exchange whatever it costs, so a large tool
		// result cannot starve the turn that has to interpret it
		MinMessages: 2,

		Estimate: func(message thread.Message) (thread.Usage, error) {
			return thread.Usage{
				Tokens: float64(tokenizer.CountMessage(e.model, message.Text())),
			}, nil
		},
	})
	if err != nil {
		return provider.Request{}, err
	}

	chat := []provider.ChatMessage{{Role: provider.RoleSystem, Content: backstory}}

	chat = append(chat, toChatMessages(fromThreadMessages(built.Messages))...)

	return provider.Request{
		Messages:  chat,
		Tools:     tools,
		MaxTokens: e.options.MaxTokens,
	}, nil
}

// backstory renders the system prompt, including the skills block.
func (e *Engine) backstory() string {
	var builder strings.Builder

	builder.WriteString(e.options.Backstory)

	if len(e.options.Skills) > 0 {
		builder.WriteString("\n\n<available_skills>\n")
		builder.WriteString("Use the following skills when appropriate. Each one's instructions live elsewhere; the access field says how to read them. Read a skill only when you decide it is relevant, then follow what it says.\n")

		for _, skill := range e.options.Skills {
			access := skill.Hint

			if access == "" {
				access = fmt.Sprintf("Read it with the `read` tool at %s.", skill.Path)
			}

			fmt.Fprintf(&builder,
				"\n<skill>\n  <name>%s</name>\n  <description>%s</description>\n  <access>%s</access>\n</skill>\n",
				skill.Name, skill.Description, access)
		}

		builder.WriteString("</available_skills>")
	}

	if e.settleMode() {
		fmt.Fprintf(&builder,
			"\n\nWhen the objective is met, call %s. If it cannot be met, call %s. "+
				"The run is not finished until you call one of them.",
			SuccessTool, FailureTool,
		)
	}

	return builder.String()
}

// toolDefinitions renders the tool schemas, adding the terminal tools in settle
// mode.
func (e *Engine) toolDefinitions() []provider.Tool {
	var tools []provider.Tool

	for name, definition := range e.options.Tools {
		tools = append(tools, provider.Tool{
			Type: "function",
			Function: provider.ToolFunction{
				Name:        name,
				Description: definition.Description,
				Parameters:  definition.Parameters,
			},
		})
	}

	if e.settleMode() {
		for _, definition := range terminalTools() {
			tools = append(tools, provider.Tool{
				Type: "function",
				Function: provider.ToolFunction{
					Name:        definition.Name,
					Description: definition.Description,
					Parameters:  definition.Parameters,
				},
			})
		}
	}

	return tools
}

func (e *Engine) finish(messages []Message, budget Budget, reason StopReason, detail string, err error) Result {
	return Result{
		Reason:   reason,
		Message:  detail,
		Messages: messages,
		Budget:   budget,
		Err:      err,
	}
}
