// Package worker provides the platform-specific Zot executable deployed by the
// command center into each sandbox.
package worker

import (
	"bytes"
	"compress/gzip"
	"embed"
	"fmt"
	"io"
	"sync"

	"github.com/openzot/openzot/internal/zotui/compute"
)

// Generated by `make worker-assets`; README.md keeps the embedded directory
// valid in a clean source checkout so tests and static analysis still compile.
//
//go:embed artifacts
var assets embed.FS

var cache sync.Map

// Load returns the embedded Zot executable for platform (for example,
// linux/amd64). Generated artifacts are gzip-compressed in the server binary
// and expanded once on first use.
func Load(platform string) (compute.Worker, error) {
	if cached, ok := cache.Load(platform); ok {
		return cached.(compute.Worker), nil
	}
	name, err := artifactName(platform)
	if err != nil {
		return compute.Worker{}, err
	}
	compressed, err := assets.ReadFile("artifacts/" + name)
	if err != nil {
		return compute.Worker{}, fmt.Errorf("worker: %s is not embedded; run make worker-assets", platform)
	}
	data, err := decode(compressed)
	if err != nil {
		return compute.Worker{}, fmt.Errorf("worker: decode %s: %w", platform, err)
	}
	worker := compute.Worker{Platform: platform, Data: data}
	cache.Store(platform, worker)
	return worker, nil
}

func artifactName(platform string) (string, error) {
	switch platform {
	case "linux/amd64":
		return "zot-linux-amd64.gz", nil
	case "linux/arm64":
		return "zot-linux-arm64.gz", nil
	default:
		return "", fmt.Errorf("worker: unsupported sandbox platform %q", platform)
	}
}

func decode(compressed []byte) ([]byte, error) {
	reader, err := gzip.NewReader(bytes.NewReader(compressed))
	if err != nil {
		return nil, err
	}
	defer reader.Close()
	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	if len(data) == 0 {
		return nil, fmt.Errorf("empty executable")
	}
	return data, nil
}
